version: '3.7'
services:

  zookeeper:
    build:
      context: ./seqpipe-zookeeper
    image: seqpipe/seqpipe-zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - type: bind
        source: ./impala_data
        target: /data

  hive_metastore:
    build:
      context: ./seqpipe-hive-metastore
    image: seqpipe/seqpipe-hive-metastore:latest
    ports:
      - "9083:9083"

    volumes:
      - type: bind
        source: ./impala_data
        target: /data
    environment:
      - SP_ZOOKEEPER=10.0.1.1
      - SP_NAMENODE=10.0.1.1
      - SP_HIVEMETASTORE=10.0.1.1

  controller:
    build:
      context: ./seqpipe-controller
    image: seqpipe/seqpipe-controller:latest
    hostname: dory.seqpipe.org
    ports:
      - "8020:8020"
      - "9870:9870"
      - "8032:8032"
      - "8033:8033"
      - "8030:8030"
      - "8031:8031"
      - "8088:8088"
      - "8090:8090"
      - "24000:24000"
      - "25010:25010"
      - "25020:25020"
      - "26000:26000"
      - "23020:23020"
    volumes:
      - type: bind
        source: ./impala_data
        target: /data
    environment:
      - SP_ZOOKEEPER=10.0.1.1
      - SP_NAMENODE=10.0.1.1
      - SP_HIVEMETASTORE=10.0.1.1
      - SP_IMPALA_STATESTORE=10.0.1.1
      - SP_IMPALA_CATALOG=10.0.1.1

  worker:
    build:
      context: ./seqpipe-worker
    image: seqpipe/seqpipe-worker:latest
    hostname: worker
    ports:
      - "9864:9864"
      - "9866:9866"
      - "21000:21000"
      - "21050:21050"
      - "22000:22000"
      - "23000:23000"
      - "25000:25000"
      - "27000:27000"
      - "28000:28000"
      - "8042:8042"
      - "45454:45454"
      - "4040:4040"
      - "7077:7077"
      - "32000-32016:32000-32016"
      - "32032:32032"
      # - "8080:8080"
    volumes:
      - type: bind
        source: ./impala_data
        target: /data
    environment:
      - SP_ZOOKEEPER=10.0.1.1
      - SP_NAMENODE=10.0.1.1
      - SP_HIVEMETASTORE=10.0.1.1
      - SP_IMPALA_STATESTORE=10.0.1.1
      - SP_IMPALA_CATALOG=10.0.1.1
      - SP_RESOURCEMANAGER=10.0.1.1
