version: '3.7'
services:

  zookeeper:
    build:
      context: ./seqpipe-zookeeper
    image: seqpipe/seqpipe-zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - type: bind
        source: ./impala_data
        target: /data
  
  namenode:
    build:
      context: ./seqpipe-namenode
    image: seqpipe/seqpipe-namenode:latest
    ports:
      - "8020:8020"
      - "9870:9870"
    volumes:
      - type: bind
        source: ./impala_data
        target: /data
    environment:
      - SP_ZOOKEEPER=10.0.1.1
      - SP_NAMENODE=10.0.1.1

  datanode:
    build:
      context: ./seqpipe-datanode
    image: seqpipe/seqpipe-datanode:latest
    ports:
      - "50075:50075"
      - "50010:50010"
      - "50020:50020"      
    volumes:
      - type: bind
        source: ./impala_data
        target: /data
    environment:
      - SP_ZOOKEEPER=10.0.1.1
      - SP_NAMENODE=10.0.1.1

  hive_metastore:
    build:
      context: ./seqpipe-hive-metastore
    image: seqpipe/seqpipe-hive-metastore:latest
    ports:
      - "9083:9083"

    volumes:
      - type: bind
        source: ./impala_data
        target: /data
    environment:
      - SP_ZOOKEEPER=10.0.1.1
      - SP_NAMENODE=10.0.1.1
      - SP_HIVEMETASTORE=10.0.1.1

  state_store:
    build:
      context: ./seqpipe-state-store
    image: seqpipe/seqpipe-state-store:latest
    ports:
      - "24000:24000"
      - "25010:25010"
    volumes:
      - type: bind
        source: ./impala_data
        target: /data
    environment:
      - SP_ZOOKEEPER=10.0.1.1
      - SP_NAMENODE=10.0.1.1
      - SP_HIVEMETASTORE=10.0.1.1
      - SP_IMPALA_STATESTORE=10.0.1.1
      - SP_IMPALA_CATALOG=10.0.1.1

  catalog:
    build:
      context: ./seqpipe-catalog
    image: seqpipe/seqpipe-catalog:latest
    ports:
      - "25020:25020"
      - "26000:26000"
      - "23020:23020"
    volumes:
      - type: bind
        source: ./impala_data
        target: /data
    environment:
      - SP_ZOOKEEPER=10.0.1.1
      - SP_NAMENODE=10.0.1.1
      - SP_HIVEMETASTORE=10.0.1.1
      - SP_IMPALA_STATESTORE=10.0.1.1
      - SP_IMPALA_CATALOG=10.0.1.1
